name: Geospatial Statistics EA
description: An external adapter to get descriptive statistics for a geospatial dataset over an area of interest.
node_identifier: geospatial-stats-ea
platforms:
  - Docker
  - AWS Lambda
  - GCP Functions
data_sources:
  - name: Shamba GeoAPI
    url: https://shamba-gateway-2ycmet71.ew.gateway.dev/geoapi/v1/docs
parameters:
  - agg_x
  - dataset_code
  - selected_band
  - geometry
  - start_date
  - end_date
  - image_scale
